
image: Visual Studio 2015

branches:
 only:
  - master
  - /^ci.*$/

platform:
  - x86

configuration:
  - Release

# Default GENERATOR is set to "Visual Studio 9 2008"
# See https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/dashboard/appveyor_dashboard.cmake
environment:
  matrix:

  - PY_VERSION: 3.7.0b2
    GENERATOR: Visual Studio 14 2015 Win64
  - PY_VERSION: 3.7.0b2
    GENERATOR: Visual Studio 14 2015

  - PY_VERSION: 3.6.5
    GENERATOR: Visual Studio 14 2015 Win64
  - PY_VERSION: 3.6.5
    GENERATOR: Visual Studio 14 2015

  - PY_VERSION: 3.5.5
    GENERATOR: Visual Studio 14 2015 Win64
  - PY_VERSION: 3.5.5
    GENERATOR: Visual Studio 14 2015

  - PY_VERSION: 2.7.14
    GENERATOR: Visual Studio 14 2015 Win64
  - PY_VERSION: 2.7.14
    GENERATOR: Visual Studio 14 2015

  - PY_VERSION: 2.7.14
    GENERATOR: Visual Studio 12 2013 Win64
  - PY_VERSION: 2.7.14
    GENERATOR: Visual Studio 12 2013

  - PY_VERSION: 2.7.14
  - PY_VERSION: 2.7.13
  - PY_VERSION: 2.7.12
  - PY_VERSION: 2.7.11
  - PY_VERSION: 2.7.10
  - PY_VERSION: 2.7.9
  - PY_VERSION: 2.7.8
  - PY_VERSION: 2.7.7
  - PY_VERSION: 2.7.6
  - PY_VERSION: 2.7.5
  - PY_VERSION: 2.7.4
  - PY_VERSION: 2.7.3

install:
  - ps: |
      $scripts_dir="$env:APPVEYOR_BUILD_FOLDER\scripts"
      mkdir $scripts_dir
      $source="https://raw.githubusercontent.com/davidsansome/python-cmake-buildsystem/dashboard/appveyor_dashboard.cmake"
      $destination="$scripts_dir\appveyor_dashboard.cmake"
      (New-Object Net.WebClient).DownloadFile($source, $destination)


build_script:
  - ctest -V -C %configuration% -S "%APPVEYOR_BUILD_FOLDER%\\scripts\\appveyor_dashboard.cmake"

test: off

deploy: off
